version: 2.0

common: &common
  working_directory: ~/repo

jobs:
  core:
    <<: *common
    docker:
      - image: davesque/rust-python:nightly-py37
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: run tests
          command: make test_rust

  py36-integration:
    <<: *common
    docker:
      - image: davesque/rust-python:nightly-py36
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: run tests
          command: pip install -r requirements-dev.txt && maturin develop && pytest

  py37-integration:
    <<: *common
    docker:
      - image: davesque/rust-python:nightly-py37
    steps:
      - checkout
      - run:
          name: merge pull request base
          command: ./.circleci/merge_pr.sh
      - run:
          name: merge pull request base (2nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: merge pull request base (3nd try)
          command: ./.circleci/merge_pr.sh
          when: on_fail
      - run:
          name: run tests
          command: pip install -r requirements-dev.txt && maturin develop && pytest

workflows:
  version: 2
  test:
    jobs:
      - core
      - py36-integration
      - py37-integration
